---
title: "Case Study"
author: "Alexis"
date: "10/10/2019"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(leaflet)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 8,
  fig.height = 6,
  out.width = "90%"
  )

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

```{r}
library(p8105.datasets)
data("nyc_airbnb")
nyc_airbnb %>% view
```

## let's answer some questions
some cleaning
```{r}
nyc_airbnb =
  nyc_airbnb %>%
  mutate(
    stars = review_scores_location / 2,
    borough = neighbourhood_group
  )
```

```{r}
nyc_airbnb %>%
  group_by(borough) %>%
  summarize(med_price = median(price, na.rm = TRUE))
```

```{r}
nyc_airbnb %>%
  group_by(borough, room_type) %>%
  summarize(med_price = median(price, na.rm = TRUE))
```

```{r}
nyc_airbnb %>%
  group_by(borough, room_type) %>%
  summarize(med_price = median(price, na.rm = TRUE)) %>%
  pivot_wider(
    names_from = room_type,
    values_from = med_price
  )
```

```{r}
nyc_airbnb %>%
  filter(borough == "Staten Island", room_type == "Shared room") %>% view
```

```{r}
nyc_airbnb %>%
  count(borough, room_type) %>%
  pivot_wider(
    names_from = room_type,
    values_from = n
  )
```

```{r}
nyc_airbnb %>%
  group_by(borough, neighbourhood) %>%
  summarize(
    mean_price = mean(price, na.rm = TRUE),
    mean_review = mean(review_scores_location, na.rm = TRUE)
  ) %>%
  ggplot(aes(x = mean_review, y = mean_price)) + 
  geom_point()
```

```{r}
nyc_airbnb %>%
  group_by(borough, neighbourhood) %>%
  summarize(
    mean_price = mean(price, na.rm = TRUE),
    mean_review = mean(review_scores_location, na.rm = TRUE)
  ) %>%
  ggplot(aes(x = mean_review, y = mean_price)) + 
  geom_point() +
  facet_grid(~borough)
```

```{r}
nyc_airbnb %>%
  count(neighbourhood)
```

price sensitivity to ratings in Astoria
```{r}
nyc_airbnb %>%
  filter(neighbourhood == "Astoria") %>%
  ggplot(aes(x = stars, y = price)) + 
  geom_point() 
```

## spatial locations

```{r}
nyc_airbnb %>%
  ggplot(aes(x = lat, y = long, color = borough)) +
  geom_point()
```

```{r}
nyc_airbnb %>%
  filter(borough == "Manhattan",
         price < 1000) %>%
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point(alpha = .3)
```


```{r}
nyc_airbnb %>%
  filter(borough == "Manhattan",
         price < 1000) %>%
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point(alpha = .3) +
  facet_grid(~room_type)
```


```{r}
nyc_airbnb %>%
  filter(
    borough == "Manhattan",
    price > 2000) %>%
    leaflet() %>%
    addTiles() %>%
    addMarkers(~lat, ~long)
```


```{r}
nyc_airbnb %>%
  filter(
    borough == "Manhattan",
    price > 2000) %>%
    leaflet() %>%
    addTiles() %>%
    addProviderTiles(providers$CartoDB.Positron) %>%
    addMarkers(~lat, ~long)
```

```{r}
nyc_airbnb %>%
  filter(
    borough == "Manhattan",
    price > 2000) %>%
    leaflet() %>%
    addTiles() %>%
    addProviderTiles(providers$CartoDB.Positron) %>%
    addCircleMarkers(~lat, ~long)
```

```{r}
pal = colorNumeric(
  palette = "viridis",
  domain = nyc_airbnb$stars)

nyc_airbnb %>%
  filter(borough == "Manhattan") %>%
  sample_n(5000) %>%
  leaflet() %>%
    addTiles() %>%
    addProviderTiles(providers$CartoDB.Positron) %>%
    addCircleMarkers(~lat, ~long, 
                     color = ~pal(stars),
                     radius = 1)
```

```{r}
pal = colorNumeric(
  palette = "viridis",
  domain = nyc_airbnb$stars)

nyc_airbnb %>%
  filter(borough == "Manhattan") %>%
  mutate(
    label = str_c("<b>Stars: ", stars, "</b><br>Price:", price, sep = "")
  ) %>%
  sample_n(5000) %>%
  leaflet() %>%
    addTiles() %>%
    addProviderTiles(providers$CartoDB.Positron) %>%
    addCircleMarkers(~lat, ~long, 
                     color = ~pal(stars),
                     radius = 1,
                     popup = ~ label)
```